---
title: "Lab06"
author: "Rafael Nóbrega Costa - RA:296730"
format: pdf
editor: visual
---

## Lab06

```{r}
library(DBI)
library(RSQLite)

path <- "C:/Users/afran/Documents/ME315"
fname <- file.path(path, "disco.db")
con <- dbConnect(RSQLite::SQLite(), fname)
```

```{r}
dbListTables(con)

dbListFields(con, "customers")
```

```{r}
dbGetQuery(con, "SELECT COUNT(*) AS total_clientes FROM customers")
```

```{sql connection=con}
SELECT Country, COUNT(*) AS total_clientes FROM customers 
GROUP BY Country 
ORDER BY total_clientes DESC
```

```{sql connection=con}
SELECT Country, COUNT(*) AS total_clientes FROM customers 
GROUP BY Country 
ORDER BY total_clientes DESC 
LIMIT 5
```

```{sql connection=con}
SELECT DISTINCT Country FROM customers 
WHERE LENGTH(Country) = 6
```

```{sql connection=con}
SELECT DISTINCT t.Name AS Musica FROM customers c
JOIN invoices i ON c.CustomerId = i.CustomerId
JOIN invoice_items ii ON i.InvoiceId = ii.InvoiceId
JOIN tracks t ON ii.TrackId = t.TrackId
WHERE c.Country = 'Brazil';
```

```{r}
dbDisconnect(con)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
