---
title: "Lista02"
author: "Rafael Nóbrega Costa - RA:296730"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
con <- dbConnect(SQLite(), "me315.sqlite")
```

## Lista 02

1.  

```{sql connection=con}
SELECT * FROM PRESERVE
ORDER BY STATE
```

2.  

```{sql connection=con}
SELECT PNAME, FEE FROM PRESERVE
WHERE STATE = "MT"
```

3.  

```{sql connection=con}
SELECT FEE, ACRES FROM PRESERVE
ORDER BY FEE, ACRES
```

4.  

```{sql connection=con}
SELECT PNAME FROM PRESERVE
ORDER BY PNO
```

5.  

```{sql connection=con}
SELECT STATE, FEE, PNO FROM PRESERVE
ORDER BY STATE DESC, FEE DESC, PNO
```

6.  

```{sql connection=con}
SELECT STATE FROM PRESERVE
WHERE STATE >= "M"
```

7.  

```{sql connection=con}
SELECT STATE FROM PRESERVE
WHERE PNAME < "TATKON"
```

9.  

```{sql connection=con}
SELECT * FROM EMPLOYEE
ORDER BY ENAME
```

10. 

```{sql connection=con}
SELECT ENAME, SALARY FROM EMPLOYEE
where salary >= 2000
order by salary desc
```

11. 

```{sql connection=con}
SELECT DNO, ENO ENAME FROM EMPLOYEE
ORDER BY DNO desc, ENO
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo") 
Sys.time()
```
